[project]
name = "connector-human-programming-interface"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "appdirs>=1.4.4",
    "click>=8.1.8",
    "decorator>=5.1.1",
    "kompress>=0.2.20240918",
    "more-itertools>=10.5.0",
    "pytz>=2024.2",
    "typing-extensions>=4.12.2",
]

[dependency-groups]
dev = [
    "build>=1.2.2.post1",
    "mypy>=1.14.1",
    "pylint>=3.3.3",
    "pytest>=8.3.4",
    "ruff>=0.8.6",
    "setuptools>=75.7.0",
    "tox>=4.23.2",
    "wheel>=0.45.1",
]
